//go:build integration

package mysql

import (
	"context"
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/testcontainers/testcontainers-go"
	tcmysql "github.com/testcontainers/testcontainers-go/modules/mysql"
	"github.com/testcontainers/testcontainers-go/wait"

	"github.com/kopecmaciej/vi-sql/internal/config"
	"github.com/kopecmaciej/vi-sql/internal/database"
	"github.com/kopecmaciej/vi-sql/internal/testutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

var testDao *Dao

func TestMain(m *testing.M) {
	ctx := context.Background()

	mysqlContainer, err := tcmysql.Run(ctx,
		"mysql:8.0.36",
		tcmysql.WithUsername("root"),
		tcmysql.WithPassword("test"),
		tcmysql.WithDatabase("auth"),
		tcmysql.WithScripts(testutil.SampleMySQLPath()),
		testutil.SeedBindMount(),
		testutil.MySQLLocalInfileMount(),
		testcontainers.WithWaitStrategy(
			wait.ForLog("port: 3306  MySQL Community Server").
				WithStartupTimeout(60*time.Second),
		),
	)
	if err != nil {
		panic("failed to start mysql container: " + err.Error())
	}
	defer mysqlContainer.Terminate(ctx) //nolint:errcheck

	connStr, err := mysqlContainer.ConnectionString(ctx)
	if err != nil {
		panic("failed to get connection string: " + err.Error())
	}

	cfg := &config.SQLConfig{
		Driver:  "mysql",
		DSN:     connStr,
		Timeout: 30,
	}
	client := NewClient(cfg)
	if err := client.Connect(ctx); err != nil {
		panic("failed to connect to mysql: " + err.Error())
	}
	defer client.Close()

	testDao = NewDao(client)
	os.Exit(m.Run())
}

// --- Schema browsing ---

func TestListSchemas(t *testing.T) {
	ctx := context.Background()

	tests := []struct {
		name   string
		filter string
		setup  func(t *testing.T)
		check  func(t *testing.T, schemas []database.Schema)
	}{
		{
			name:   "returns multiple schemas",
			filter: "",
			check: func(t *testing.T, schemas []database.Schema) {
				schemaNames := make([]string, len(schemas))
				for i, s := range schemas {
					schemaNames[i] = s.Schema
				}
				assert.Contains(t, schemaNames, "auth")
				assert.Contains(t, schemaNames, "catalog")
			},
		},
		{
			name:   "filter by name",
			filter: "auth",
			check: func(t *testing.T, schemas []database.Schema) {
				require.NotEmpty(t, schemas)
				for _, s := range schemas {
					assert.Contains(t, s.Schema, "auth")
				}
			},
		},
		{
			name:   "includes views",
			filter: "auth",
			setup: func(t *testing.T) {
				_, err := testDao.ExecuteStatement(ctx,
					"CREATE OR REPLACE VIEW auth.v_test_users AS SELECT id, email FROM auth.users")
				require.NoError(t, err)
			},
			check: func(t *testing.T, schemas []database.Schema) {
				require.Len(t, schemas, 1)
				assert.Contains(t, schemas[0].Views, "v_test_users")
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if tt.setup != nil {
				tt.setup(t)
			}
			schemas, err := testDao.ListSchemas(ctx, tt.filter)
			require.NoError(t, err)
			tt.check(t, schemas)
		})
	}
}

func TestGetViewDDL_ReturnsDefinition(t *testing.T) {
	ctx := context.Background()

	_, err := testDao.ExecuteStatement(ctx,
		"CREATE OR REPLACE VIEW auth.v_ddl_test AS SELECT id, email FROM auth.users")
	require.NoError(t, err)

	ddl, err := testDao.GetViewDDL(ctx, "auth", "v_ddl_test")
	require.NoError(t, err)
	assert.NotEmpty(t, ddl)
	assert.Contains(t, ddl, "users")
}

// --- Table structure ---

func TestGetTableColumns_WithMySQLTypes(t *testing.T) {
	ctx := context.Background()

	cols, err := testDao.GetTableColumns(ctx, "auth", "users")
	require.NoError(t, err)
	require.NotEmpty(t, cols)

	for _, c := range cols {
		assert.NotEmpty(t, c.Name)
		assert.NotEmpty(t, c.DataType)
	}
}

func TestGetTableColumns_AutoIncrementIsAutoGenerated(t *testing.T) {
	ctx := context.Background()

	_, err := testDao.ExecuteStatement(ctx,
		"CREATE TABLE IF NOT EXISTS auth.auto_gen_test (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL)")
	require.NoError(t, err)
	defer testDao.ExecuteStatement(ctx, "DROP TABLE IF EXISTS auth.auto_gen_test") //nolint:errcheck

	cols, err := testDao.GetTableColumns(ctx, "auth", "auto_gen_test")
	require.NoError(t, err)

	var idCol, nameCol *database.ColumnInfo
	for i := range cols {
		switch cols[i].Name {
		case "id":
			idCol = &cols[i]
		case "name":
			nameCol = &cols[i]
		}
	}
	require.NotNil(t, idCol)
	require.NotNil(t, nameCol)
	assert.True(t, idCol.IsAutoGenerated, "AUTO_INCREMENT column must be marked IsAutoGenerated")
	assert.False(t, nameCol.IsAutoGenerated, "plain column must not be marked IsAutoGenerated")
}

func TestGetTableConstraints(t *testing.T) {
	ctx := context.Background()

	// auth.users has PRIMARY KEY and UNIQUE constraints
	constraints, err := testDao.GetTableConstraints(ctx, "auth", "users")
	require.NoError(t, err)
	require.NotEmpty(t, constraints)
}

func TestGetTableForeignKeys(t *testing.T) {
	ctx := context.Background()

	// auth.user_roles has FKs to users and roles
	fks, err := testDao.GetTableForeignKeys(ctx, "auth", "user_roles")
	require.NoError(t, err)
	require.NotEmpty(t, fks)
}

// --- Row CRUD ---

func TestListRows_BasicPagination(t *testing.T) {
	ctx := context.Background()

	state := database.NewTableState("auth", "users")
	state.BatchSize = 3

	_, rows, err := testDao.FetchTableRows(ctx, state, "", "")
	require.NoError(t, err)
	assert.LessOrEqual(t, len(rows), 3)
}

func TestExecuteQuery_Select(t *testing.T) {
	ctx := context.Background()

	rows, cols, err := testDao.ExecuteQuery(ctx,
		"SELECT * FROM `auth`.`users` LIMIT 2")
	require.NoError(t, err)
	assert.NotEmpty(t, cols)
	_ = rows
}

func TestExecuteStatement_CreateDrop(t *testing.T) {
	ctx := context.Background()

	affected, err := testDao.ExecuteStatement(ctx,
		"CREATE TABLE IF NOT EXISTS `auth`.`my_stmt_test` (id INT NOT NULL AUTO_INCREMENT, PRIMARY KEY (id))")
	require.NoError(t, err)
	assert.GreaterOrEqual(t, affected, int64(0))

	_, err = testDao.ExecuteStatement(ctx, "DROP TABLE IF EXISTS `auth`.`my_stmt_test`")
	require.NoError(t, err)
}

func TestExplainQuery_ReturnsOutput(t *testing.T) {
	ctx := context.Background()

	plan, err := testDao.ExplainPlan(ctx, "SELECT 1")
	require.NoError(t, err)
	assert.NotEmpty(t, plan)
}

// --- Indexes ---

func TestCreateIndex_GetIndexes_DropIndex(t *testing.T) {
	ctx := context.Background()

	_, err := testDao.ExecuteStatement(ctx,
		"CREATE TABLE IF NOT EXISTS `auth`.`idx_my_test` (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255), PRIMARY KEY (id))")
	require.NoError(t, err)
	defer testDao.ExecuteStatement(ctx, "DROP TABLE IF EXISTS `auth`.`idx_my_test`") //nolint:errcheck

	def := database.IndexDefinition{
		Name:     "idx_my_test_name",
		Columns:  []string{"name"},
		IsUnique: false,
	}
	err = testDao.CreateIndex(ctx, "auth", "idx_my_test", def)
	require.NoError(t, err)

	indexes, err := testDao.GetIndexes(ctx, "auth", "idx_my_test")
	require.NoError(t, err)

	var found bool
	for _, idx := range indexes {
		if idx.Name == "idx_my_test_name" {
			found = true
		}
	}
	assert.True(t, found, "created index should appear in GetIndexes")

	err = testDao.DropIndex(ctx, "auth", "idx_my_test_name")
	require.NoError(t, err)
}

// --- DDL ---

func TestCreateTable_And_DropTable(t *testing.T) {
	ctx := context.Background()

	ddl := "CREATE TABLE `auth`.`my_ddl_test` (id INT NOT NULL AUTO_INCREMENT, label VARCHAR(255) NOT NULL, PRIMARY KEY (id))"
	err := testDao.CreateTable(ctx, "auth", ddl)
	require.NoError(t, err)

	schemas, err := testDao.ListSchemas(ctx, "auth")
	require.NoError(t, err)
	var found bool
	for _, s := range schemas {
		if s.Schema == "auth" {
			for _, tbl := range s.Tables {
				if tbl == "my_ddl_test" {
					found = true
				}
			}
		}
	}
	assert.True(t, found, "created table should appear in schema listing")

	err = testDao.DropTable(ctx, "auth", "my_ddl_test")
	require.NoError(t, err)
}

func TestTruncateTable(t *testing.T) {
	ctx := context.Background()

	_, err := testDao.ExecuteStatement(ctx,
		"CREATE TABLE IF NOT EXISTS `auth`.`trunc_my_test` (id INT NOT NULL AUTO_INCREMENT, PRIMARY KEY (id))")
	require.NoError(t, err)
	defer testDao.ExecuteStatement(ctx, "DROP TABLE IF EXISTS `auth`.`trunc_my_test`") //nolint:errcheck

	_, err = testDao.ExecuteStatement(ctx,
		"INSERT INTO `auth`.`trunc_my_test` (id) VALUES (NULL)")
	require.NoError(t, err)

	err = testDao.TruncateTable(ctx, "auth", "trunc_my_test")
	require.NoError(t, err)

	state := database.NewTableState("auth", "trunc_my_test")
	state.BatchSize = 100
	_, rows, err := testDao.FetchTableRows(ctx, state, "", "")
	require.NoError(t, err)
	assert.Empty(t, rows)
}

// --- Server info ---

func TestGetServerInfo_ReturnsVersion(t *testing.T) {
	ctx := context.Background()

	info, err := testDao.GetServerInfo(ctx)
	require.NoError(t, err)
	assert.Contains(t, info.Version, "MySQL")
}

func TestGetActiveSessions_PositiveCount(t *testing.T) {
	ctx := context.Background()

	sessions, err := testDao.GetActiveSessions(ctx)
	require.NoError(t, err)
	assert.Greater(t, sessions, int64(0))
}

// --- Autocomplete ---

func TestGetTableColumnNames(t *testing.T) {
	ctx := context.Background()

	names, err := testDao.GetTableColumnNames(ctx, "auth", "users")
	require.NoError(t, err)
	assert.NotEmpty(t, names)
}

// --- Driver info ---

func TestCommonDataTypes_NonEmpty(t *testing.T) {
	types := testDao.CommonDataTypes()
	assert.NotEmpty(t, types)
}

func TestDefaultCreateTableDDL_ContainsTableName(t *testing.T) {
	ddl := testDao.DefaultCreateTableDDL("auth", "my_my_table")
	assert.Contains(t, ddl, "my_my_table")
}

// --- Row CRUD (insert / update / delete) ---

func TestInsertRow_UpdateRow_DeleteRow(t *testing.T) {
	ctx := context.Background()

	_, err := testDao.ExecuteStatement(ctx,
		`CREATE TABLE IF NOT EXISTS `+"`auth`.`crud_my_test`"+` (
			id    INT          NOT NULL AUTO_INCREMENT,
			label VARCHAR(255) NOT NULL,
			PRIMARY KEY (id)
		)`)
	require.NoError(t, err)
	defer testDao.ExecuteStatement(ctx, "DROP TABLE IF EXISTS `auth`.`crud_my_test`") //nolint:errcheck

	newRow := database.Row{"label": "hello"}
	pk, err := testDao.InsertRow(ctx, "auth", "crud_my_test", newRow)
	require.NoError(t, err)

	rows, _, err := testDao.ExecuteQuery(ctx,
		fmt.Sprintf("SELECT label FROM `auth`.`crud_my_test` WHERE id = %v", pk.Columns["id"]))
	require.NoError(t, err)
	require.Len(t, rows, 1)
	original := rows[0]
	assert.Equal(t, "hello", original["label"])

	updated := make(database.Row)
	for k, v := range original {
		updated[k] = v
	}
	updated["label"] = "world"
	updated["id"] = pk.Columns["id"]
	err = testDao.UpdateRow(ctx, "auth", "crud_my_test", pk, original, updated)
	require.NoError(t, err)

	rows, _, err = testDao.ExecuteQuery(ctx,
		fmt.Sprintf("SELECT label FROM `auth`.`crud_my_test` WHERE id = %v", pk.Columns["id"]))
	require.NoError(t, err)
	require.Len(t, rows, 1)
	assert.Equal(t, "world", rows[0]["label"])

	err = testDao.DeleteRows(ctx, "auth", "crud_my_test", []database.PrimaryKey{pk})
	require.NoError(t, err)

	rows, _, err = testDao.ExecuteQuery(ctx,
		fmt.Sprintf("SELECT id FROM `auth`.`crud_my_test` WHERE id = %v", pk.Columns["id"]))
	require.NoError(t, err)
	assert.Empty(t, rows, "row should not exist after delete")
}

// --- FetchTableRows with filtering ---

func TestListRows_WithWhere(t *testing.T) {
	ctx := context.Background()

	_, err := testDao.ExecuteStatement(ctx,
		"CREATE TABLE IF NOT EXISTS `auth`.`filter_my_test` (id INT NOT NULL AUTO_INCREMENT, status VARCHAR(50) NOT NULL, PRIMARY KEY (id))")
	require.NoError(t, err)
	defer testDao.ExecuteStatement(ctx, "DROP TABLE IF EXISTS `auth`.`filter_my_test`") //nolint:errcheck

	_, err = testDao.ExecuteStatement(ctx,
		"INSERT INTO `auth`.`filter_my_test` (status) VALUES ('active'),('inactive'),('active')")
	require.NoError(t, err)

	state := database.NewTableState("auth", "filter_my_test")
	state.BatchSize = 100

	_, rows, err := testDao.FetchTableRows(ctx, state, "status = 'active'", "")
	require.NoError(t, err)
	require.NotEmpty(t, rows)
	for _, r := range rows {
		assert.Equal(t, "active", r["status"])
	}
}

func TestListRows_WithOrderBy(t *testing.T) {
	ctx := context.Background()

	_, err := testDao.ExecuteStatement(ctx,
		"CREATE TABLE IF NOT EXISTS `auth`.`order_my_test` (id INT NOT NULL AUTO_INCREMENT, label VARCHAR(255) NOT NULL, PRIMARY KEY (id))")
	require.NoError(t, err)
	defer testDao.ExecuteStatement(ctx, "DROP TABLE IF EXISTS `auth`.`order_my_test`") //nolint:errcheck

	_, err = testDao.ExecuteStatement(ctx,
		"INSERT INTO `auth`.`order_my_test` (label) VALUES ('charlie'),('alpha'),('bravo')")
	require.NoError(t, err)

	state := database.NewTableState("auth", "order_my_test")
	state.BatchSize = 100

	_, rows, err := testDao.FetchTableRows(ctx, state, "", "label ASC")
	require.NoError(t, err)
	require.NotEmpty(t, rows)
	for i := 1; i < len(rows); i++ {
		prev := rows[i-1]["label"].(string)
		curr := rows[i]["label"].(string)
		assert.LessOrEqual(t, prev, curr, "rows should be ordered by label ASC")
	}
}

// --- RenameTable ---

func TestRenameTable_And_RenameBack(t *testing.T) {
	ctx := context.Background()

	_, err := testDao.ExecuteStatement(ctx,
		"CREATE TABLE IF NOT EXISTS `auth`.`rename_my_src` (id INT NOT NULL AUTO_INCREMENT, PRIMARY KEY (id))")
	require.NoError(t, err)
	defer testDao.ExecuteStatement(ctx, "DROP TABLE IF EXISTS `auth`.`rename_my_src`") //nolint:errcheck
	defer testDao.ExecuteStatement(ctx, "DROP TABLE IF EXISTS `auth`.`rename_my_dst`") //nolint:errcheck

	err = testDao.RenameTable(ctx, "auth", "rename_my_src", "rename_my_dst")
	require.NoError(t, err)

	schemas, err := testDao.ListSchemas(ctx, "auth")
	require.NoError(t, err)
	var tables []string
	for _, s := range schemas {
		if s.Schema == "auth" {
			tables = s.Tables
		}
	}
	assert.Contains(t, tables, "rename_my_dst")
	assert.NotContains(t, tables, "rename_my_src")

	err = testDao.RenameTable(ctx, "auth", "rename_my_dst", "rename_my_src")
	require.NoError(t, err)
}

func TestGetEstimatedRowCount(t *testing.T) {
	ctx := context.Background()

	count, _, err := testDao.GetEstimatedRowCount(ctx, "auth", "users")
	require.NoError(t, err)
	assert.GreaterOrEqual(t, count, int64(0))
}

func TestRenameColumn(t *testing.T) {
	ctx := context.Background()

	require.NoError(t, testDao.CreateTable(ctx, "auth",
		"CREATE TABLE `auth`.`rename_col_my` (id INT NOT NULL AUTO_INCREMENT, old_name VARCHAR(255), PRIMARY KEY (id))"))
	defer testDao.DropTable(ctx, "auth", "rename_col_my") //nolint:errcheck

	err := testDao.RenameColumn(ctx, "auth", "rename_col_my", "old_name", "new_name")
	require.NoError(t, err)

	names, err := testDao.GetTableColumnNames(ctx, "auth", "rename_col_my")
	require.NoError(t, err)
	assert.Contains(t, names, "new_name")
	assert.NotContains(t, names, "old_name")
}

// --- FetchQueryRows ---

func TestListQueryRows_WithPagination(t *testing.T) {
	ctx := context.Background()

	_, rows, cols, err := testDao.FetchQueryRows(ctx,
		"SELECT * FROM `auth`.`users`", 2, 0)
	require.NoError(t, err)
	assert.NotEmpty(t, cols)
	assert.LessOrEqual(t, len(rows), 2)
}

func TestListQueryRows_NoLimit_Paginates(t *testing.T) {
	ctx := context.Background()

	const batch = 3
	_, rows, _, err := testDao.FetchQueryRows(ctx, "SELECT * FROM `auth`.`users`", batch, 0)
	require.NoError(t, err)
	assert.LessOrEqual(t, len(rows), batch, "first page must not exceed batch size")
	assert.NotEmpty(t, rows)

	_, rows2, _, err := testDao.FetchQueryRows(ctx, "SELECT * FROM `auth`.`users`", batch, batch)
	require.NoError(t, err)
	assert.Len(t, rows2, batch, "second page should also have a full batch")
}

func TestListQueryRows_WithUserLimit_Paginates(t *testing.T) {
	ctx := context.Background()

	const batch = 2

	_, page1, _, err := testDao.FetchQueryRows(ctx,
		"SELECT * FROM `auth`.`users` LIMIT 5", batch, 0)
	require.NoError(t, err)
	assert.Len(t, page1, batch, "first page should return batch rows")

	_, page2, _, err := testDao.FetchQueryRows(ctx,
		"SELECT * FROM `auth`.`users` LIMIT 5", batch, batch)
	require.NoError(t, err)
	assert.Len(t, page2, batch, "second page should return batch rows")

	// Third page: offset=4 (batch*2), so only 1 row remains out of userLimit=5.
	_, page3, _, err := testDao.FetchQueryRows(ctx,
		"SELECT * FROM `auth`.`users` LIMIT 5", batch, batch*2)
	require.NoError(t, err)
	assert.Len(t, page3, 1, "last page should have the remainder row")
}
