package sql

import (
	"fmt"
	"strings"

	"github.com/kopecmaciej/vi-sql/internal/database"
	"github.com/kopecmaciej/vi-sql/internal/util"
)

// BuildInsertSQL generates an INSERT template for the given table. Auto-generated
// columns (serial/identity) are omitted; columns with overridable defaults are
// pre-filled with those defaults; nullable columns use NULL; required columns
// get a comment placeholder. quote controls identifier quoting for the target dialect.
func BuildInsertSQL(schema, table string, columns []database.ColumnInfo, quote util.Quoter) string {
	var colNames []string
	var valuePlaceholders []string
	var skipped []string

	for _, col := range columns {
		if col.IsAutoGenerated {
			skipped = append(skipped, fmt.Sprintf("%s (%s)", col.Name, col.DataType))
			continue
		}
		colNames = append(colNames, "    "+quote.Ident(col.Name))
		switch {
		case col.Default != nil && isEmittableDefault(*col.Default):
			valuePlaceholders = append(valuePlaceholders, fmt.Sprintf("    %s", *col.Default))
		case col.IsNullable:
			valuePlaceholders = append(valuePlaceholders, "    NULL")
		default:
			valuePlaceholders = append(valuePlaceholders, fmt.Sprintf("    '' -- REQUIRED: %s (%s)", col.Name, col.DataType))
		}
	}

	header := ""
	if len(skipped) > 0 {
		header = fmt.Sprintf("-- Auto-filled (omitted): %s\n", strings.Join(skipped, ", "))
	}

	return fmt.Sprintf("%sINSERT INTO %s (\n%s\n) VALUES (\n%s\n);",
		header, quote.Table(schema, table),
		strings.Join(colNames, ",\n"),
		strings.Join(valuePlaceholders, ",\n"))
}

// BuildDuplicateInsertSQL generates an INSERT statement pre-filled with all
// values from row. orderedNames controls column order; colMeta maps name →
// ColumnInfo for default detection; literal converts a cell value to a SQL
// literal string. quote controls identifier quoting for the target dialect.
func BuildDuplicateInsertSQL(
	schema, table string,
	orderedNames []string,
	colMeta map[string]database.ColumnInfo,
	literal func(any) string,
	row database.Row,
	quote util.Quoter,
) string {
	var colNames []string
	var valuePlaceholders []string
	var skipped []string

	for _, name := range orderedNames {
		col := colMeta[name]
		if col.IsAutoGenerated {
			skipped = append(skipped, fmt.Sprintf("%s (%s)", col.Name, col.DataType))
			continue
		}
		colNames = append(colNames, "    "+quote.Ident(name))
		valuePlaceholders = append(valuePlaceholders, fmt.Sprintf("    %s", literal(row[name])))
	}

	header := ""
	if len(skipped) > 0 {
		header = fmt.Sprintf("-- Auto-filled (omitted): %s\n", strings.Join(skipped, ", "))
	}

	return fmt.Sprintf("%sINSERT INTO %s (\n%s\n) VALUES (\n%s\n);",
		header, quote.Table(schema, table),
		strings.Join(colNames, ",\n"),
		strings.Join(valuePlaceholders, ",\n"))
}

// BuildUpdateSQL generates an UPDATE statement pre-filled with row values.
// pkCols are excluded from the SET clause and used in the WHERE clause.
// literal converts a cell value to a SQL literal string. quote controls
// identifier quoting for the target dialect.
func BuildUpdateSQL(
	schema, table string,
	orderedCols []string,
	pkCols []string,
	literal func(any) string,
	row database.Row,
	pk database.PrimaryKey,
	quote util.Quoter,
) string {
	pkSet := make(map[string]bool, len(pkCols))
	for _, col := range pkCols {
		pkSet[col] = true
	}

	var setClauses []string
	for _, col := range orderedCols {
		if pkSet[col] {
			continue
		}
		setClauses = append(setClauses, fmt.Sprintf("    %s = %s", quote.Ident(col), literal(row[col])))
	}

	var whereParts []string
	for _, pkCol := range pkCols {
		whereParts = append(whereParts, fmt.Sprintf("%s = %s", quote.Ident(pkCol), literal(pk.Columns[pkCol])))
	}

	return fmt.Sprintf("UPDATE %s\nSET\n%s\nWHERE %s;",
		quote.Table(schema, table),
		strings.Join(setClauses, ",\n"),
		strings.Join(whereParts, " AND "))
}

// isEmittableDefault reports whether a column_default value can be emitted
// verbatim into an INSERT template. Empty values, unterminated quotes,
// unbalanced parentheses, statement separators and comment markers would
// produce broken SQL, so those fall back to the NULL / required placeholders
// instead. The pseudo-default "AUTO_INCREMENT" reported by MySQL-compatible
// catalogs for identity columns is rejected as well.
func isEmittableDefault(def string) bool {
	s := strings.TrimSpace(def)
	if s == "" || strings.EqualFold(s, "auto_increment") {
		return false
	}
	depth := 0
	inSingle, inDouble := false, false
	for i := 0; i < len(s); i++ {
		switch c := s[i]; {
		case inSingle:
			if c == '\'' {
				inSingle = false
			}
		case inDouble:
			if c == '"' {
				inDouble = false
			}
		case c == '\'':
			inSingle = true
		case c == '"':
			inDouble = true
		case c == '(':
			depth++
		case c == ')':
			depth--
			if depth < 0 {
				return false
			}
		case c == ';':
			return false
		case c == '-' && i+1 < len(s) && s[i+1] == '-':
			return false
		case c == '/' && i+1 < len(s) && s[i+1] == '*':
			return false
		}
	}
	return !inSingle && !inDouble && depth == 0
}
