package sql

import (
	"testing"

	"github.com/kopecmaciej/vi-sql/internal/database"
	"github.com/kopecmaciej/vi-sql/internal/util"
	"github.com/stretchr/testify/assert"
)

func ptr(s string) *string { return &s }

func TestBuildInsertSQL_SkipsAutoGeneratedColumn(t *testing.T) {
	cols := []database.ColumnInfo{
		{Name: "id", DataType: "int", IsAutoGenerated: true, IsPK: true},
		{Name: "label", DataType: "text", IsNullable: true},
	}
	sql := BuildInsertSQL("dbo", "t", cols, util.ANSIQuoter)
	assert.NotContains(t, sql, `"id"`)
	assert.Contains(t, sql, `"label"`)
	assert.Contains(t, sql, "Auto-filled (omitted): id (int)")
}

func TestBuildInsertSQL_SkipsNextvalDefault(t *testing.T) {
	cols := []database.ColumnInfo{
		{Name: "id", DataType: "int4", IsAutoGenerated: true, Default: ptr("nextval('t_id_seq'::regclass)")},
		{Name: "label", DataType: "text", IsNullable: true},
	}
	sql := BuildInsertSQL("public", "t", cols, util.ANSIQuoter)
	assert.NotContains(t, sql, `"id"`)
	assert.Contains(t, sql, `"label"`)
}

func TestBuildInsertSQL_MySQLUsesBackticks(t *testing.T) {
	cols := []database.ColumnInfo{
		{Name: "id", DataType: "int", IsAutoGenerated: true, IsPK: true},
		{Name: "label", DataType: "text", IsNullable: true},
	}
	sql := BuildInsertSQL("shipping", "test", cols, util.BacktickQuoter)
	assert.Contains(t, sql, "`shipping`.`test`")
	assert.Contains(t, sql, "`label`")
	assert.NotContains(t, sql, `"label"`)
}

// A NOT NULL column without a default must produce an editable placeholder
// (not a bare comment, which would make the whole VALUES list a syntax error).
func TestBuildInsertSQL_RequiredColumnHasEditablePlaceholder(t *testing.T) {
	cols := []database.ColumnInfo{
		{Name: "name", DataType: "varchar(30)", IsNullable: false},
	}
	sql := BuildInsertSQL("public", "t", cols, util.ANSIQuoter)
	assert.Contains(t, sql, "'' -- REQUIRED: name (varchar(30))")
}

func TestBuildDuplicateInsertSQL_SkipsAutoGeneratedColumn(t *testing.T) {
	cols := map[string]database.ColumnInfo{
		"id":    {Name: "id", DataType: "int", IsAutoGenerated: true, IsPK: true},
		"label": {Name: "label", DataType: "text", IsNullable: true},
	}
	row := database.Row{"id": int64(1), "label": "hello"}
	sql := BuildDuplicateInsertSQL("dbo", "t", []string{"id", "label"}, cols, func(v any) string {
		if s, ok := v.(string); ok {
			return "'" + s + "'"
		}
		return "1"
	}, row, util.ANSIQuoter)
	assert.NotContains(t, sql, `"id"`)
	assert.Contains(t, sql, `"label"`)
}

func TestBuildInsertSQL_UnsafeDefaultFallsBack(t *testing.T) {
	def := "broken -- comment"
	columns := []database.ColumnInfo{
		{Name: "id", DataType: "int", IsNullable: true, Default: &def},
	}

	got := BuildInsertSQL("s", "t", columns, util.ANSIQuoter)

	assert.Contains(t, got, "NULL", "unsafe default must fall back to NULL")
	assert.NotContains(t, got, "broken")
}

func TestBuildInsertSQL_SafeDefaultsKeptVerbatim(t *testing.T) {
	strDef := "'abc'"
	exprDef := "(now())"
	quotedCommentDef := "'a--b'"
	autoIncDef := "AUTO_INCREMENT"
	columns := []database.ColumnInfo{
		{Name: "a", Default: &strDef},
		{Name: "b", Default: &exprDef},
		{Name: "c", Default: &quotedCommentDef},
		{Name: "d", IsNullable: true, Default: &autoIncDef},
	}

	got := BuildInsertSQL("s", "t", columns, util.BacktickQuoter)

	assert.Contains(t, got, "'abc'")
	assert.Contains(t, got, "(now())")
	assert.Contains(t, got, "'a--b'", "comment marker inside quotes must be kept")
	assert.NotContains(t, got, "AUTO_INCREMENT", "pseudo-default must fall back")
	assert.Contains(t, got, "NULL")
}
