package sql

import (
	"testing"

	"github.com/kopecmaciej/vi-sql/internal/database"
	"github.com/kopecmaciej/vi-sql/internal/util"
	"github.com/stretchr/testify/assert"
)

func ptr(s string) *string { return &s }

func TestBuildInsertSQL_SkipsAutoGeneratedColumn(t *testing.T) {
	cols := []database.ColumnInfo{
		{Name: "id", DataType: "int", IsAutoGenerated: true, IsPK: true},
		{Name: "label", DataType: "text", IsNullable: true},
	}
	sql := BuildInsertSQL("dbo", "t", cols, util.ANSIQuoter)
	assert.NotContains(t, sql, `"id"`)
	assert.Contains(t, sql, `"label"`)
	assert.Contains(t, sql, "Auto-filled (omitted): id (int)")
}

func TestBuildInsertSQL_SkipsNextvalDefault(t *testing.T) {
	cols := []database.ColumnInfo{
		{Name: "id", DataType: "int4", IsAutoGenerated: true, Default: ptr("nextval('t_id_seq'::regclass)")},
		{Name: "label", DataType: "text", IsNullable: true},
	}
	sql := BuildInsertSQL("public", "t", cols, util.ANSIQuoter)
	assert.NotContains(t, sql, `"id"`)
	assert.Contains(t, sql, `"label"`)
}

func TestBuildInsertSQL_MySQLUsesBackticks(t *testing.T) {
	cols := []database.ColumnInfo{
		{Name: "id", DataType: "int", IsAutoGenerated: true, IsPK: true},
		{Name: "label", DataType: "text", IsNullable: true},
	}
	sql := BuildInsertSQL("shipping", "test", cols, util.BacktickQuoter)
	assert.Contains(t, sql, "`shipping`.`test`")
	assert.Contains(t, sql, "`label`")
	assert.NotContains(t, sql, `"label"`)
}

func TestBuildInsertSQL_MultipleRequiredColumnComment(t *testing.T) {
	cols := []database.ColumnInfo{
		{Name: "user_id", DataType: "uuid", IsNullable: false},
		{Name: "note", DataType: "text", IsNullable: true},
		{Name: "name", DataType: "varchar(30)", IsNullable: false},
		{Name: "fingerprint", DataType: "character varying", IsNullable: false},
	}
	want := "    '', -- REQUIRED: user_id (uuid)\n" +
		"    NULL,\n" +
		"    '', -- REQUIRED: name (varchar(30))\n" +
		"    '' -- REQUIRED: fingerprint (character varying)\n);"
	sql := BuildInsertSQL("public", "t", cols, util.ANSIQuoter)
	assert.Contains(t, sql, want)
}

func TestBuildDuplicateInsertSQL_SkipsAutoGeneratedColumn(t *testing.T) {
	cols := map[string]database.ColumnInfo{
		"id":    {Name: "id", DataType: "int", IsAutoGenerated: true, IsPK: true},
		"label": {Name: "label", DataType: "text", IsNullable: true},
	}
	row := database.Row{"id": int64(1), "label": "hello"}
	sql := BuildDuplicateInsertSQL("dbo", "t", []string{"id", "label"}, cols, func(v any) string {
		if s, ok := v.(string); ok {
			return "'" + s + "'"
		}
		return "1"
	}, row, util.ANSIQuoter)
	assert.NotContains(t, sql, `"id"`)
	assert.Contains(t, sql, `"label"`)
}
