package sql

import (
	"fmt"
	"strings"

	"github.com/kopecmaciej/vi-sql/internal/database"
)

// IsAutoGenerated reports whether a column default is managed entirely by the
// server and cannot/should not be overridden in a plain INSERT statement.
// Covers: serial (nextval), GENERATED ALWAYS AS IDENTITY.
func IsAutoGenerated(def *string) bool {
	if def == nil {
		return false
	}
	lower := strings.ToLower(*def)
	return strings.Contains(lower, "nextval(") || strings.Contains(lower, "generated always")
}

// BuildInsertSQL generates an INSERT template for the given table. Auto-generated
// columns (serial/identity) are omitted; columns with overridable defaults are
// pre-filled with those defaults; nullable columns use NULL; required columns
// get a comment placeholder.
func BuildInsertSQL(schema, table string, columns []database.ColumnInfo) string {
	var colNames []string
	var valuePlaceholders []string
	var skipped []string

	for _, col := range columns {
		if IsAutoGenerated(col.Default) {
			skipped = append(skipped, fmt.Sprintf("%s (%s)", col.Name, col.DataType))
			continue
		}
		colNames = append(colNames, fmt.Sprintf("    \"%s\"", col.Name))
		switch {
		case col.Default != nil:
			valuePlaceholders = append(valuePlaceholders, fmt.Sprintf("    %s", *col.Default))
		case col.IsNullable:
			valuePlaceholders = append(valuePlaceholders, "    NULL")
		default:
			valuePlaceholders = append(valuePlaceholders, fmt.Sprintf("    -- REQUIRED: %s (%s)", col.Name, col.DataType))
		}
	}

	header := ""
	if len(skipped) > 0 {
		header = fmt.Sprintf("-- Auto-filled (omitted): %s\n", strings.Join(skipped, ", "))
	}

	return fmt.Sprintf("%sINSERT INTO \"%s\".\"%s\" (\n%s\n) VALUES (\n%s\n);",
		header, schema, table,
		strings.Join(colNames, ",\n"),
		strings.Join(valuePlaceholders, ",\n"))
}

// BuildDuplicateInsertSQL generates an INSERT statement pre-filled with all
// values from row. orderedNames controls column order; colMeta maps name →
// ColumnInfo for default detection; literal converts a cell value to a SQL
// literal string.
func BuildDuplicateInsertSQL(
	schema, table string,
	orderedNames []string,
	colMeta map[string]database.ColumnInfo,
	literal func(any) string,
	row database.Row,
) string {
	var colNames []string
	var valuePlaceholders []string
	var skipped []string

	for _, name := range orderedNames {
		col := colMeta[name]
		if IsAutoGenerated(col.Default) {
			skipped = append(skipped, fmt.Sprintf("%s (%s)", col.Name, col.DataType))
			continue
		}
		colNames = append(colNames, fmt.Sprintf("    \"%s\"", name))
		valuePlaceholders = append(valuePlaceholders, fmt.Sprintf("    %s", literal(row[name])))
	}

	header := ""
	if len(skipped) > 0 {
		header = fmt.Sprintf("-- Auto-filled (omitted): %s\n", strings.Join(skipped, ", "))
	}

	return fmt.Sprintf("%sINSERT INTO \"%s\".\"%s\" (\n%s\n) VALUES (\n%s\n);",
		header, schema, table,
		strings.Join(colNames, ",\n"),
		strings.Join(valuePlaceholders, ",\n"))
}

// BuildUpdateSQL generates an UPDATE statement pre-filled with row values.
// pkCols are excluded from the SET clause and used in the WHERE clause.
// literal converts a cell value to a SQL literal string.
func BuildUpdateSQL(
	schema, table string,
	orderedCols []string,
	pkCols []string,
	literal func(any) string,
	row database.Row,
	pk database.PrimaryKey,
) string {
	pkSet := make(map[string]bool, len(pkCols))
	for _, col := range pkCols {
		pkSet[col] = true
	}

	var setClauses []string
	for _, col := range orderedCols {
		if pkSet[col] {
			continue
		}
		setClauses = append(setClauses, fmt.Sprintf("    \"%s\" = %s", col, literal(row[col])))
	}

	var whereParts []string
	for _, pkCol := range pkCols {
		whereParts = append(whereParts, fmt.Sprintf("\"%s\" = %s", pkCol, literal(pk.Columns[pkCol])))
	}

	return fmt.Sprintf("UPDATE \"%s\".\"%s\"\nSET\n%s\nWHERE %s;",
		schema, table,
		strings.Join(setClauses, ",\n"),
		strings.Join(whereParts, " AND "))
}
