package manager

import (
	"sync"
	"time"

	"github.com/gdamore/tcell/v2"
	"github.com/kopecmaciej/tview"
)

const (
	FocusChanged           MessageType = "focus_changed"
	StyleChanged           MessageType = "style_changed"
	UpdateAutocompleteKeys MessageType = "update_autocomplete"
	UpdateQueryBar         MessageType = "update_query_bar"
	FooterHeightChanged    MessageType = "footer_height_changed"
	MCPStateChanged        MessageType = "mcp_state_changed"
	OpenQueryTab           MessageType = "open_query_tab"
	OpenTableTab           MessageType = "open_table_tab"
	QueryExecuted          MessageType = "query_executed"
)

type (
	// OpenQueryTabRequest is broadcast by the MCP open_query_in_tab tool.
	// TabID is pre-generated by the MCP tool so it can be returned to the caller
	// immediately. Name is the optional display label; empty means auto "Query N".
	OpenQueryTabRequest struct {
		TabID string
		Query string
		Name  string
	}

	// TableTabRequest is broadcast when FK navigation needs to open a new table tab.
	TableTabRequest struct {
		Schema string
		Table  string
		Where  string
	}

	// QueryResult is broadcast after the user executes a query and also
	// returned directly by the get_last_query_result MCP tool.
	QueryResult struct {
		Query      string           `json:"query"`
		Columns    []string         `json:"columns,omitempty"`
		Rows       []map[string]any `json:"rows,omitempty"`
		RowCount   int              `json:"row_count"`
		Affected   int64            `json:"affected_rows,omitempty"`
		ExecutedAt *time.Time       `json:"executed_at,omitempty"`
	}

	MessageType string

	Message struct {
		Type MessageType
		Data any
	}

	EventMsg struct {
		*tcell.EventKey
		Sender  tview.Identifier
		Message Message
	}

	ElementManager struct {
		mutex     sync.Mutex
		listeners map[tview.Identifier]chan EventMsg
	}
)

func NewElementManager() *ElementManager {
	return &ElementManager{
		mutex:     sync.Mutex{},
		listeners: make(map[tview.Identifier]chan EventMsg),
	}
}

func (eh *ElementManager) Subscribe(element tview.Identifier) chan EventMsg {
	eh.mutex.Lock()
	defer eh.mutex.Unlock()
	listener := make(chan EventMsg, 1)
	eh.listeners[element] = listener
	return listener
}

func (eh *ElementManager) Unsubscribe(element tview.Identifier, listener chan EventMsg) {
	eh.mutex.Lock()
	defer eh.mutex.Unlock()
	delete(eh.listeners, element)
}

func (eh *ElementManager) Broadcast(event EventMsg) {
	eh.mutex.Lock()
	channels := make([]chan EventMsg, 0, len(eh.listeners))
	for _, ch := range eh.listeners {
		channels = append(channels, ch)
	}
	eh.mutex.Unlock()

	for _, ch := range channels {
		go func(c chan EventMsg) { c <- event }(ch)
	}
}

func (eh *ElementManager) SendTo(element tview.Identifier, event EventMsg) {
	eh.mutex.Lock()
	ch, exists := eh.listeners[element]
	eh.mutex.Unlock()
	if exists {
		go func() { ch <- event }()
	}
}
